var ActionTypes = {
    CHANGE_ORIGIN_AMOUNT: "CHANGE_ORIGIN_AMOUNT",
    CHANGE_DEST_AMOUNT: "CHANGE_DEST_AMOUNT",
    CHANGE_ORIGIN_CURR: "CHANGE_ORIGIN_CURR",
    CHANGE_TO_CURR: "CHANGE_TO_CURR"
}

export default ActionTypes;